services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: beach_product
      MYSQL_ROOT_PASSWORD: root
      TZ: "America/Sao_Paulo"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -proot --silent"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-java
    depends_on:
      db:
        condition: service_healthy
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=docker"
    ports:
      - "8080:8080"

volumes:
  mysql_data:
